/**
 * Error codes for storage operations
 */
export enum StorageErrorCode {
  // Configuration errors
  STORAGE_CONFIGURATION_ERROR = 'STORAGE_CONFIGURATION_ERROR',

  // Operation errors
  STORAGE_UPLOAD_ERROR = 'STORAGE_UPLOAD_ERROR',
  STORAGE_DOWNLOAD_ERROR = 'STORAGE_DOWNLOAD_ERROR',
  STORAGE_DELETE_ERROR = 'STORAGE_DELETE_ERROR',
  STORAGE_LIST_ERROR = 'STORAGE_LIST_ERROR',

  // File errors
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_ALREADY_EXISTS = 'FILE_ALREADY_EXISTS',
  INVALID_FILE_TYPE = 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // Provider errors
  STORAGE_PROVIDER_ERROR = 'STORAGE_PROVIDER_ERROR',
  STORAGE_PROVIDER_TIMEOUT = 'STORAGE_PROVIDER_TIMEOUT',

  // Validation errors
  STORAGE_VALIDATION_ERROR = 'STORAGE_VALIDATION_ERROR',
  INVALID_KEY = 'INVALID_KEY',

  // Permission errors
  STORAGE_PERMISSION_ERROR = 'STORAGE_PERMISSION_ERROR',
  STORAGE_ACCESS_DENIED = 'STORAGE_ACCESS_DENIED',

  // General errors
  STORAGE_ERROR = 'STORAGE_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
